const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let scanData=[];
let db=JSON.parse(localStorage.getItem('fbaScoutProducts')||'[]');
let assumptions=JSON.parse(localStorage.getItem('fbaScoutAssumptions')||'null');
let loadTimer=null,loadStep=0,resultFilter='all';
const MARKET={UK:{symbol:'£',currency:'GBP',vat:20},US:{symbol:'$',currency:'USD',vat:0},DE:{symbol:'€',currency:'EUR',vat:19}};
const DEFAULTS={shipping:1.8,duty:.35,prep:.45,referral:15,fba:3.25,ppc:3,storage:.18,returns:.6,moq:200,target:29.99};
const loadSteps=[['Открываю сайт поставщика','Проверяю страницу и ищу карточки товаров'],['Собираю товары','Читаю названия, фото, цены и ссылки'],['Сравниваю с Amazon','Ищу существующие листинги и цены'],['Проверяю ограничения','Отмечаю категории с approval, compliance и FBA-рисками'],['Считаю экономику','Прибыль, маржа, ROI, break-even и капитал партии']];

function market(){return $('market')?.value||'UK'}
function symbol(){return MARKET[market()]?.symbol||'£'}
function money(v,s=symbol()){return s+(Number(v)||0).toFixed(2)}
function parsePrice(v){const n=parseFloat(String(v||'').replace(/[^0-9.,-]/g,'').replace(',','.'));return Number.isFinite(n)?n:0}
function persist(){localStorage.setItem('fbaScoutProducts',JSON.stringify(db));renderDb()}
function saveAssumptions(){assumptions={shipping:+$('aShipping').value||0,duty:+$('aDuty').value||0,prep:+$('aPrep').value||0,referral:+$('aReferral').value||0,fba:+$('aFba').value||0,vat:+$('aVat').value||0,ppc:+$('aPpc').value||0,storage:+$('aStorage').value||0,returns:+$('aReturns').value||0,moq:+$('aMoq').value||0,target:+$('aTarget').value||0};localStorage.setItem('fbaScoutAssumptions',JSON.stringify(assumptions))}
function resetAssumptions(){const m=MARKET[market()]||MARKET.UK;assumptions={...DEFAULTS,vat:m.vat};for(const [id,key] of [['aShipping','shipping'],['aDuty','duty'],['aPrep','prep'],['aReferral','referral'],['aFba','fba'],['aVat','vat'],['aPpc','ppc'],['aStorage','storage'],['aReturns','returns'],['aMoq','moq'],['aTarget','target']])$(id).value=assumptions[key];saveAssumptions()}
function initAssumptions(){if(!assumptions)resetAssumptions();else{for(const [id,key] of [['aShipping','shipping'],['aDuty','duty'],['aPrep','prep'],['aReferral','referral'],['aFba','fba'],['aVat','vat'],['aPpc','ppc'],['aStorage','storage'],['aReturns','returns'],['aMoq','moq'],['aTarget','target']])$(id).value=assumptions[key]??0}}

function calc(x){const landed=(+x.unitCost||0)+(+x.shipping||0)+(+x.duty||0)+(+x.prep||0),price=+x.salePrice||0,ref=price*((+x.referral||0)/100),vat=price*((+x.vat||0)/(100+(+x.vat||0))),fixed=(+x.fba||0)+(+x.ppc||0)+(+x.storage||0)+(+x.returns||0)+landed,profit=price-vat-ref-fixed,margin=price?profit/price*100:0,roi=landed?profit/landed*100:0,factor=1-((+x.referral||0)/100)-((+x.vat||0)/(100+(+x.vat||0))),breakEven=factor>0?fixed/factor:0,maxPpc=(+x.ppc||0)+profit,batchCapital=landed*(+x.moq||0),batchProfit=profit*(+x.moq||0);return{landed,profit,margin,roi,breakEven,maxPpc,batchCapital,batchProfit}}
function median(arr){const xs=arr.filter(n=>n>0).sort((a,b)=>a-b);if(!xs.length)return 0;const mid=Math.floor(xs.length/2);return xs.length%2?xs[mid]:(xs[mid-1]+xs[mid])/2}
function comparablePrice(x){return median((x.amazon?.items||[]).map(y=>parsePrice(y.price)))}
function initModel(x){if(x.model)return;const a=assumptions||{...DEFAULTS,vat:MARKET[market()].vat};const sourceCurrency=(x.currency||'').toUpperCase(),targetCurrency=MARKET[market()].currency;const supplierParsed=parsePrice(x.price);const unitCost=sourceCurrency&&sourceCurrency===targetCurrency?supplierParsed:0;const foundPrice=parsePrice(x.amazon?.best?.price);const comp=comparablePrice(x);x.model={unitCost,salePrice:foundPrice||comp||a.target,shipping:a.shipping,duty:a.duty,prep:a.prep,referral:a.referral,fba:a.fba,vat:a.vat,ppc:a.ppc,storage:a.storage,returns:a.returns,moq:a.moq}}

function complianceFor(name,mkt=market()){
  const s=String(name||'').toLowerCase();
  const prohibited=/switchblade|automatic knife|balisong|butterfly knife|gravity knife|push dagger|stiletto|concealed sword|spring-loaded knife/;
  const blades=/knife|knives|blade|machete|sword|razor|dagger|cutlery/;
  const battery=/battery|lithium|power bank|charger|rechargeable/;
  const baby=/baby|infant|toddler|kids|children/;
  const food=/food|supplement|vitamin|gummy|protein|tea|coffee|snack/;
  const cosmetic=/cosmetic|cream|serum|lotion|makeup|shampoo|perfume/;
  const medical=/medical|diagnostic|therapy|therapeutic|surgical|prescription/;
  const electrical=/electric|electrical|electronic|adapter|plug|heater|lamp/;
  if(prohibited.test(s))return{level:'blocked',label:'Высокий риск запрета',reasons:['Название похоже на тип клинкового товара, который может быть запрещён правилами Amazon или местным законодательством.','Не закупать до проверки конкретного продукта и marketplace в Seller Central.'],fba:'Не подтверждено'};
  if(blades.test(s))return{level:'restricted',label:'Ограниченная категория',reasons:mkt==='UK'?['Клинковые товары в Amazon UK имеют отдельные правила, возрастные ограничения и ограничения по fulfillment.','Некоторые разрешённые клинковые товары могут требовать knife flag/approval и FBA.','Точное право продажи зависит от конкретного товара и Seller-аккаунта.']:['Клинковые товары требуют отдельной проверки restricted-products policy для выбранного marketplace.','Точное разрешение зависит от типа товара и Seller-аккаунта.'],fba:mkt==='UK'?'Только отдельные допустимые типы':'Проверить'};
  if(medical.test(s))return{level:'restricted',label:'Compliance / approval',reasons:['Медицинские товары могут требовать approval, документы и подтверждение заявлений.','Нужна проверка product type и marketplace requirements.'],fba:'Проверить'};
  if(food.test(s)||cosmetic.test(s)||baby.test(s)||battery.test(s)||electrical.test(s)){const r=[];if(food.test(s))r.push('Пищевые товары и добавки часто требуют специальных документов, маркировки и category compliance.');if(cosmetic.test(s))r.push('Косметика может требовать ingredient/safety documentation и локальное соответствие.');if(baby.test(s))r.push('Детские товары часто требуют product-safety тесты и документы.');if(battery.test(s))r.push('Батареи/литий могут попасть под Dangerous Goods и транспортные ограничения FBA.');if(electrical.test(s))r.push('Электротовары требуют проверки локальных стандартов, вилки, маркировки и safety docs.');return{level:'review',label:'Нужна проверка документов',reasons:r,fba:'Вероятно после compliance'} }
  return{level:'prelim',label:'Предварительно возможно',reasons:['По названию не видно очевидной restricted-категории.','Это не является окончательным разрешением Amazon. Seller eligibility нужно подтвердить в Seller Central/SP-API.'],fba:'Предварительно возможно'}
}
function absenceReasons(x,c){const out=[];if(x.amazon?.state==='not_found'){out.push('Точного совпадения по названию не найдено в автоматическом поиске Amazon.');out.push('Товар может быть новым для Amazon, продаваться под другим названием или как вариация другого ASIN.');if(c.level!=='prelim')out.push('Категорийные ограничения или compliance могут быть одной из причин отсутствия листинга.');out.push('Отсутствие листинга само по себе не доказывает спрос или прибыльность.')}if(x.amazon?.state==='unverified')out.push('Amazon не дал надёжный автоматический ответ, поэтому отсутствие товара не подтверждено.');return out}

function startLoading(){clearInterval(loadTimer);loadStep=0;$('loader').classList.add('show');$('scanBtn').disabled=true;paintLoading();loadTimer=setInterval(()=>{loadStep=Math.min(loadStep+1,loadSteps.length-1);paintLoading()},2200)}
function paintLoading(){const [a,b]=loadSteps[loadStep];$('loaderTitle').textContent=a;$('loaderSub').textContent=b;$('progressBar').style.width=((loadStep+1)/loadSteps.length*94)+'%';document.querySelectorAll('.step').forEach((e,i)=>e.classList.toggle('active',i<=loadStep))}
function stopLoading(ok=true){clearInterval(loadTimer);$('scanBtn').disabled=false;$('progressBar').style.width='100%';$('loaderTitle').textContent=ok?'Готово':'Анализ остановлен';$('loaderSub').textContent=ok?'Все доступные данные собраны ниже':'Смотри сообщение ниже';setTimeout(()=>$('loader').classList.remove('show'),1200)}
async function scan(){const url=$('scanUrl').value.trim();if(!url)return alert('Вставь URL поставщика');saveAssumptions();startLoading();$('scanResults').innerHTML='';$('sourceInfo').textContent='Анализируем...';try{const r=await fetch('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url,marketplace:market(),maxProducts:+$('maxProducts').value})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Сервер вернул некорректный ответ')};if(data.error)throw new Error(data.details||data.error);scanData=(data.products||[]).map(x=>({...x}));scanData.forEach(initModel);$('sourceInfo').textContent=(data.source?.host||url)+(data.warning?' · '+data.warning:'');renderScan();stopLoading(true)}catch(e){scanData=[];$('scanResults').innerHTML='<div class="empty">Не удалось проанализировать: '+esc(e.message)+'</div>';$('sourceInfo').textContent='Ошибка анализа';renderSummary();stopLoading(false)}}
function renderSummary(){const found=scanData.filter(x=>x.amazon?.state==='found').length,notFound=scanData.filter(x=>x.amazon?.state==='not_found').length,unverified=scanData.filter(x=>x.amazon?.state==='unverified').length;$('sTotal').textContent=scanData.length;$('sFound').textContent=found;$('sNew').textContent=notFound;$('sUnverified').textContent=unverified}
function filterResults(list){return resultFilter==='all'?list:list.filter(x=>x.amazon?.state===resultFilter)}
function statusBadge(st){return st==='found'?'<span class="badge found">✓ Есть на Amazon</span>':st==='not_found'?'<span class="badge not_found">✕ Не найден на Amazon</span>':'<span class="badge unverified">? Нужно проверить</span>'}
function complianceBadge(c){return `<span class="risk ${c.level}">${esc(c.label)}</span>`}
function field(label,val,index,key,step='.01'){return `<label class="econField"><span>${label}</span><input type="number" step="${step}" value="${Number(val)||0}" onchange="updateModel(${index},'${key}',this.value)"></label>`}
function renderScan(){renderSummary();const list=filterResults(scanData);if(!scanData.length){$('scanResults').innerHTML='<div class="empty">Товары на этой странице не найдены. Попробуй категорию с карточками товаров или конкретную карточку.</div>';return}if(!list.length){$('scanResults').innerHTML='<div class="empty">В этой группе товаров нет.</div>';return}$('scanResults').innerHTML=list.map(x=>{const i=scanData.indexOf(x),a=x.amazon||{},best=a.best||{},m=x.model||{},c=complianceFor(x.name),e=calc(m),found=a.state==='found',rawPrice=x.price?`${x.price}${x.currency?' '+x.currency:''}`:'Цена не прочитана',comp=a.items||[],reasons=absenceReasons(x,c);return `<article class="productCard">
<div class="productTop"><div class="pic">${x.image?`<img src="${esc(x.image)}" alt="">`:'Нет фото'}</div><div class="supplierBlock"><div class="eyebrow">ПОСТАВЩИК</div><h3>${esc(x.name)}</h3><div class="rawPrice">${esc(rawPrice)}</div><div class="links"><a href="${esc(x.url||$('scanUrl').value)}" target="_blank">Открыть товар ↗</a></div></div><div class="amazonBlock"><div class="eyebrow">AMAZON</div>${statusBadge(a.state)}${found?`<h4>${esc(best.title||x.name)}</h4><div class="amazonPrice">${esc(best.price||'Цена не прочитана')}</div><div class="links"><a href="${esc(best.url||a.searchUrl||'#')}" target="_blank">Листинг ↗</a><a href="${esc(a.searchUrl||'#')}" target="_blank">Поиск ↗</a></div>`:`<h4>${a.state==='not_found'?'Точного листинга не нашли':'Автопроверка не подтверждена'}</h4><p>${a.state==='not_found'?'Можно рассматривать как потенциально новый листинг, но сначала проверяем ограничения, спрос и экономику.':'Нужно открыть поиск Amazon вручную, прежде чем считать товар отсутствующим.'}</p><div class="links"><a href="${esc(a.searchUrl||'#')}" target="_blank">Проверить Amazon ↗</a></div>`}</div><div class="eligibilityBlock"><div class="eyebrow">МОЖНО ЛИ ЗАВЕСТИ</div>${complianceBadge(c)}<b>${esc(c.fba)}</b><p>Предварительная проверка категории. Account-specific approval пока не подключён.</p></div></div>
<div class="analysisGrid"><section class="economics"><div class="sectionHead"><div><div class="eyebrow">FBA ECONOMICS</div><h4>Экономика на 1 шт.</h4></div><span class="calcNote">редактируй цифры</span></div><div class="econFields">${field('Закупка',m.unitCost,i,'unitCost')}${field('Цена продажи',m.salePrice,i,'salePrice')}${field('Доставка',m.shipping,i,'shipping')}${field('Пошлина',m.duty,i,'duty')}${field('Prep',m.prep,i,'prep')}${field('FBA fee',m.fba,i,'fba')}${field('PPC',m.ppc,i,'ppc')}${field('MOQ',m.moq,i,'moq','1')}</div><div class="metrics" id="metrics-${i}">${metricsHtml(e,m)}</div>${!m.unitCost&&x.price?`<div class="callout warnCallout">Цена поставщика найдена как <b>${esc(rawPrice)}</b>, но валюта не совпадает/не подтверждена. Введи закупочную цену в валюте Amazon.</div>`:''}</section>
<section class="checks"><div class="eyebrow">РИСКИ И ОГРАНИЧЕНИЯ</div><h4>${esc(c.label)}</h4><ul>${c.reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul>${reasons.length?`<div class="why"><b>Почему товара может не быть на Amazon</b><ul>${reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></div>`:''}${comp.length&&!found?`<details><summary>Ближайшие товары Amazon (${comp.length})</summary>${comp.slice(0,3).map(y=>`<a class="comparable" href="${esc(y.url)}" target="_blank"><span>${esc(y.title)}</span><b>${esc(y.price||'—')}</b><small>${y.similarity||0}% совпадения</small></a>`).join('')}</details>`:''}</section></div>
<div class="productFoot"><div><span class="miniLabel">Вывод</span><b>${e.profit>0&&e.roi>30&&c.level==='prelim'?'Экономика выглядит интересной, нужна проверка спроса и Seller eligibility.':e.profit>0?'Есть потенциальная прибыль, но остаются риски/неполные данные.':'С текущими цифрами товар не даёт достаточной экономики.'}</b></div><button class="btn secondary" onclick="saveCandidate(${i})">Сохранить в базу</button></div></article>`}).join('')}
function metricsHtml(e,m){return `<div><span>Landed cost</span><b>${money(e.landed)}</b></div><div><span>Profit / шт</span><b class="${e.profit>=0?'green':'red'}">${money(e.profit)}</b></div><div><span>Margin</span><b>${e.margin.toFixed(1)}%</b></div><div><span>ROI</span><b class="${e.roi>=30?'green':e.roi<0?'red':''}">${e.roi.toFixed(1)}%</b></div><div><span>Break-even price</span><b>${money(e.breakEven)}</b></div><div><span>Max PPC</span><b>${money(e.maxPpc)}</b></div><div><span>Капитал партии</span><b>${money(e.batchCapital)}</b></div><div><span>Прибыль партии</span><b class="${e.batchProfit>=0?'green':'red'}">${money(e.batchProfit)}</b></div>`}
function updateModel(i,key,val){if(!scanData[i])return;scanData[i].model[key]=parseFloat(val)||0;const box=$('metrics-'+i);if(box)box.innerHTML=metricsHtml(calc(scanData[i].model),scanData[i].model)}

function saveCandidate(i){const x=scanData[i],a=x.amazon||{},b=a.best||{},c=complianceFor(x.name),m=x.model||{};db.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),name:x.name||'Без названия',status:'research',amazonState:a.state,supplierUrl:x.url||$('scanUrl').value,amazonUrl:b.url||a.searchUrl||'',asin:b.asin||'',marketplace:market(),supplierRawPrice:x.price||'',supplierCurrency:x.currency||'',supplierPrice:+m.unitCost||0,amazonPrice:+m.salePrice||0,moq:+m.moq||0,shipping:+m.shipping||0,duty:+m.duty||0,prep:+m.prep||0,referral:+m.referral||15,fba:+m.fba||0,vat:+m.vat||0,ppc:+m.ppc||0,storage:+m.storage||0,returns:+m.returns||0,compliance:c,notes:a.state==='found'?'Найден существующий Amazon листинг.':a.state==='not_found'?'Точный листинг не найден. Проверить как новый листинг.':'Amazon не удалось проверить автоматически.',updatedAt:Date.now()});persist();alert('Товар сохранён в базу')}
function renderDb(){let list=[...db],q=$('search')?.value?.toLowerCase()||'',st=$('statusFilter')?.value||'all';if(q)list=list.filter(x=>JSON.stringify(x).toLowerCase().includes(q));if(st!=='all')list=list.filter(x=>x.status===st);const dbCalc=x=>calc({unitCost:x.supplierPrice,shipping:x.shipping,duty:x.duty,prep:x.prep,salePrice:x.amazonPrice,referral:x.referral,fba:x.fba,vat:x.vat,ppc:x.ppc,storage:x.storage,returns:x.returns,moq:x.moq});if($('sort')?.value==='roi')list.sort((a,b)=>dbCalc(b).roi-dbCalc(a).roi);else if($('sort')?.value==='profit')list.sort((a,b)=>dbCalc(b).profit-dbCalc(a).profit);else list.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));$('dbRows').innerHTML=list.map(x=>{const c=dbCalc(x);return `<div class="row"><div class="name">${esc(x.name)}</div><div>${money(x.amazonPrice,MARKET[x.marketplace]?.symbol||'£')}</div><div>${money(c.landed,MARKET[x.marketplace]?.symbol||'£')}</div><div class="${c.profit>=0?'green':'red'}">${money(c.profit,MARKET[x.marketplace]?.symbol||'£')}</div><div>${c.margin.toFixed(1)}%</div><div>${c.roi.toFixed(1)}%</div><div>${esc(x.status||'research')}</div></div>`}).join('');$('dbEmpty').classList.toggle('hidden',!!list.length);$('dbTotal').textContent=db.length;$('dbShort').textContent=db.filter(x=>x.status==='shortlist').length;const cs=db.map(dbCalc);$('dbRoi').textContent=(cs.length?cs.reduce((s,c)=>s+c.roi,0)/cs.length:0).toFixed(1)+'%';$('dbProfit').textContent=money(cs.length?cs.reduce((s,c)=>s+c.profit,0)/cs.length:0)}
function switchView(v){$('scannerView').classList.toggle('hidden',v!=='scanner');$('databaseView').classList.toggle('hidden',v!=='database');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='database')renderDb()}

document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>switchView(x.dataset.view));document.querySelectorAll('.filter').forEach(x=>x.onclick=()=>{resultFilter=x.dataset.resultFilter;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===x));renderScan()});$('scanBtn').onclick=scan;$('resetAssumptions').onclick=resetAssumptions;$('market').onchange=()=>{resetAssumptions()};['aShipping','aDuty','aPrep','aReferral','aFba','aVat','aPpc','aStorage','aReturns','aMoq','aTarget'].forEach(id=>$(id).addEventListener('change',saveAssumptions));['search','statusFilter','sort'].forEach(id=>$(id).addEventListener('input',renderDb));initAssumptions();renderDb();
