const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const money=v=>'£'+(Number(v)||0).toFixed(2);let scanData=[];let db=JSON.parse(localStorage.getItem('fbaScoutProducts')||'[]');let loadTimer=null,loadStep=0;
const loadSteps=[['Открываю сайт поставщика','Проверяю страницу и ищу карточки товаров'],['Собираю товары','Читаю названия, фото, цены и ссылки'],['Сравниваю с Amazon','Ищу этот же товар на выбранном Amazon'],['Проверяю совпадения','Разделяю найденные и не найденные товары'],['Собираю результат','Готовлю понятный список по каждому товару']];
function persist(){localStorage.setItem('fbaScoutProducts',JSON.stringify(db));renderDb()}
function calc(x){const landed=(+x.supplierPrice||0)+(+x.shipping||0)+(+x.duty||0)+(+x.prep||0),price=+x.amazonPrice||0,ref=price*((+x.referral||15)/100),vat=price*((+x.vat||20)/(100+(+x.vat||20))),profit=price-vat-ref-(+x.fba||0)-(+x.ppc||0)-(+x.storage||0)-(+x.returns||0)-landed;return{landed,profit,margin:price?profit/price*100:0,roi:landed?profit/landed*100:0}}
function startLoading(){clearInterval(loadTimer);loadStep=0;$('loader').classList.add('show');$('scanBtn').disabled=true;paintLoading();loadTimer=setInterval(()=>{loadStep=Math.min(loadStep+1,loadSteps.length-1);paintLoading()},2200)}
function paintLoading(){const [a,b]=loadSteps[loadStep];$('loaderTitle').textContent=a;$('loaderSub').textContent=b;$('progressBar').style.width=((loadStep+1)/loadSteps.length*92)+'%';document.querySelectorAll('.step').forEach((e,i)=>e.classList.toggle('active',i<=loadStep))}
function stopLoading(ok=true){clearInterval(loadTimer);$('scanBtn').disabled=false;$('progressBar').style.width='100%';$('loaderTitle').textContent=ok?'Готово':'Сканирование остановлено';$('loaderSub').textContent=ok?'Сравнение закончено':'Смотри сообщение об ошибке ниже';setTimeout(()=>$('loader').classList.remove('show'),1100)}
async function scan(){const url=$('scanUrl').value.trim();if(!url)return alert('Вставь URL поставщика');startLoading();$('scanResults').innerHTML='';$('sourceInfo').textContent='Сканируем...';try{const r=await fetch('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url,marketplace:$('market').value,maxProducts:+$('maxProducts').value})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Сервер вернул некорректный ответ')};if(data.error)throw new Error(data.details||data.error);scanData=data.products||[];$('sourceInfo').textContent=(data.source?.host||url)+(data.warning?' · '+data.warning:'');renderScan();stopLoading(true)}catch(e){scanData=[];$('scanResults').innerHTML='<div class="empty">Не удалось просканировать: '+esc(e.message)+'</div>';$('sourceInfo').textContent='Ошибка сканирования';renderSummary();stopLoading(false)}}
function renderSummary(){const found=scanData.filter(x=>x.amazon?.state==='found').length;const notFound=scanData.length-found;$('sTotal').textContent=scanData.length;$('sFound').textContent=found;if($('sSimilar'))$('sSimilar').textContent='—';$('sNew').textContent=notFound}
function renderScan(){renderSummary();if(!scanData.length){$('scanResults').innerHTML='<div class="empty">Товары на этой странице не найдены. Попробуй ссылку на категорию или конкретную карточку товара.</div>';return}$('scanResults').innerHTML=scanData.map((x,i)=>{const a=x.amazon||{},best=a.best||{},found=a.state==='found';return `<div class="product"><div class="pic">${x.image?`<img src="${esc(x.image)}" alt="">`:'Нет фото'}</div><div class="productInfo"><div class="eyebrow">Товар у поставщика</div><h3>${esc(x.name)}</h3><div class="supplierPrice ${x.price?'':'mutedPrice'}">${x.price?esc(x.price):'Цена не найдена'}</div><div class="links"><a href="${esc(x.url||'#')}" target="_blank">Открыть у поставщика ↗</a></div></div><div class="amazonBox"><div class="eyebrow">Проверка Amazon</div>${found?`<span class="badge found">✓ Есть на Amazon</span><div class="amazonMini"><b>${esc(best.title||x.name)}</b><div class="amazonPrice ${best.price?'':'mutedPrice'}">${best.price?esc(best.price):'Цена не найдена'}</div></div><div class="links" style="margin-top:10px"><a href="${esc(best.url||a.searchUrl||'#')}" target="_blank">Открыть листинг ↗</a><a href="${esc(a.searchUrl||'#')}" target="_blank">Поиск Amazon ↗</a></div>`:`<span class="badge not_found">✕ Не найден на Amazon</span><div class="amazonMini"><b>Совпадающий товар не найден</b><span>По автоматической проверке этот товар на Amazon не найден.</span></div><div class="links" style="margin-top:10px"><a href="${esc(a.searchUrl||'#')}" target="_blank">Проверить вручную ↗</a></div>`}</div><div class="productSide"><div><div class="eyebrow">Результат</div><div class="small">${found?'Есть совпадающий листинг Amazon.':'Совпадающего листинга не нашли.'}</div></div><div class="actions"><button class="btn secondary" onclick="saveCandidate(${i})">Сохранить</button></div></div></div>`}).join('')}
function saveCandidate(i){const x=scanData[i],a=x.amazon||{},b=a.best||{};db.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),name:x.name||'Без названия',status:'research',supplierUrl:x.url||$('scanUrl').value,amazonUrl:b.url||a.searchUrl||'',asin:b.asin||'',marketplace:$('market').value,supplierPrice:parseFloat(x.price)||0,amazonPrice:parseFloat(String(b.price||'').replace(/[^0-9.,]/g,'').replace(',','.'))||0,moq:0,shipping:0,duty:0,prep:0,referral:15,fba:0,vat:20,ppc:0,storage:0,returns:0,notes:a.state==='found'?'Товар найден на Amazon.':'Товар не найден на Amazon по автоматической проверке.',updatedAt:Date.now()});persist();alert('Добавлено в базу')}
function saveAll(){scanData.forEach((_,i)=>saveCandidate(i))}
function renderDb(){let list=[...db],q=$('search')?.value?.toLowerCase()||'',st=$('statusFilter')?.value||'all';if(q)list=list.filter(x=>JSON.stringify(x).toLowerCase().includes(q));if(st!=='all')list=list.filter(x=>x.status===st);if($('sort')?.value==='roi')list.sort((a,b)=>calc(b).roi-calc(a).roi);else if($('sort')?.value==='profit')list.sort((a,b)=>calc(b).profit-calc(a).profit);else list.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));$('dbRows').innerHTML=list.map(x=>{const c=calc(x);return `<div class="row"><div class="name">${esc(x.name)}</div><div>${money(x.amazonPrice)}</div><div>${money(c.landed)}</div><div class="${c.profit>=0?'green':'red'}">${money(c.profit)}</div><div>${c.margin.toFixed(1)}%</div><div>${c.roi.toFixed(1)}%</div><div>${esc(x.status||'research')}</div></div>`}).join('');$('dbEmpty').classList.toggle('hidden',!!list.length);$('dbTotal').textContent=db.length;$('dbShort').textContent=db.filter(x=>x.status==='shortlist').length;const cs=db.map(calc);$('dbRoi').textContent=(cs.length?cs.reduce((s,c)=>s+c.roi,0)/cs.length:0).toFixed(1)+'%';$('dbProfit').textContent=money(cs.length?cs.reduce((s,c)=>s+c.profit,0)/cs.length:0)}
function switchView(v){$('scannerView').classList.toggle('hidden',v!=='scanner');$('databaseView').classList.toggle('hidden',v!=='database');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='database')renderDb()}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>switchView(x.dataset.view));$('scanBtn').onclick=scan;$('saveAll').onclick=saveAll;['search','statusFilter','sort'].forEach(id=>$(id).addEventListener('input',renderDb));renderDb();