const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const money=v=>'£'+(Number(v)||0).toFixed(2);let scanData=[];let db=JSON.parse(localStorage.getItem('fbaScoutProducts')||'[]');let loadTimer=null,loadStep=0;
const loadSteps=[['Открываю сайт поставщика','Проверяю доступ к странице и каталогу'],['Собираю товары','Ищу названия, ссылки, цены и изображения'],['Сравниваю с Amazon','Проверяю совпадения и похожие листинги'],['Ищу новые возможности','Отмечаю товары без точного совпадения'],['Собираю результат','Готовлю карточки и ссылки для проверки']];
function persist(){localStorage.setItem('fbaScoutProducts',JSON.stringify(db));renderDb()}
function calc(x){const landed=(+x.supplierPrice||0)+(+x.shipping||0)+(+x.duty||0)+(+x.prep||0),price=+x.amazonPrice||0,ref=price*((+x.referral||15)/100),vat=price*((+x.vat||20)/(100+(+x.vat||20))),profit=price-vat-ref-(+x.fba||0)-(+x.ppc||0)-(+x.storage||0)-(+x.returns||0)-landed;return{landed,profit,margin:price?profit/price*100:0,roi:landed?profit/landed*100:0}}
function startLoading(){clearInterval(loadTimer);loadStep=0;$('loader').classList.add('show');$('scanBtn').disabled=true;paintLoading();loadTimer=setInterval(()=>{loadStep=Math.min(loadStep+1,loadSteps.length-1);paintLoading()},2200)}
function paintLoading(){const [a,b]=loadSteps[loadStep];$('loaderTitle').textContent=a;$('loaderSub').textContent=b;$('progressBar').style.width=((loadStep+1)/loadSteps.length*92)+'%';document.querySelectorAll('.step').forEach((e,i)=>e.classList.toggle('active',i<=loadStep))}
function stopLoading(ok=true){clearInterval(loadTimer);$('scanBtn').disabled=false;$('progressBar').style.width='100%';$('loaderTitle').textContent=ok?'Готово':'Сканирование остановлено';$('loaderSub').textContent=ok?'Результаты собраны ниже':'Смотри сообщение об ошибке ниже';setTimeout(()=>$('loader').classList.remove('show'),1100)}
async function scan(){const url=$('scanUrl').value.trim();if(!url)return alert('Вставь URL поставщика');startLoading();$('scanResults').innerHTML='';$('sourceInfo').textContent='Сканируем...';try{const r=await fetch('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url,marketplace:$('market').value,maxProducts:+$('maxProducts').value})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{throw new Error('Сервер вернул некорректный ответ')};if(data.error)throw new Error(data.details||data.error);scanData=data.products||[];$('sourceInfo').textContent=(data.source?.host||url)+(data.warning?' · '+data.warning:'');renderScan();stopLoading(true)}catch(e){scanData=[];$('scanResults').innerHTML='<div class="empty">Не удалось просканировать: '+esc(e.message)+'</div>';$('sourceInfo').textContent='Ошибка сканирования';renderSummary();stopLoading(false)}}
function renderSummary(){const found=scanData.filter(x=>x.amazon?.state==='found').length,sim=scanData.filter(x=>x.amazon?.state==='similar').length,newc=scanData.filter(x=>['not_found','needs_review'].includes(x.amazon?.state)).length;$('sTotal').textContent=scanData.length;$('sFound').textContent=found;$('sSimilar').textContent=sim;$('sNew').textContent=newc}
function renderScan(){renderSummary();if(!scanData.length){$('scanResults').innerHTML='<div class="empty">Товары не найдены. Попробуй страницу категории или конкретную карточку товара.</div>';return}$('scanResults').innerHTML=scanData.map((x,i)=>{const a=x.amazon||{},best=a.best||{},st=a.state||'needs_review',label={found:'Есть на Amazon',similar:'Похожий товар',not_found:'Точного совпадения нет',needs_review:'Проверить вручную'}[st];return `<div class="product"><div class="pic">${x.image?`<img src="${esc(x.image)}">`:'◻'}</div><div><h3>${esc(x.name)}</h3><div class="links"><a href="${esc(x.url||'#')}" target="_blank">Поставщик ↗</a><a href="${esc(a.searchUrl||'#')}" target="_blank">Amazon поиск ↗</a></div></div><div class="amazonMini"><span class="badge ${st}">${label}</span>${best.title?`<b>${esc(best.title)}</b><span>${esc(best.price||'Цена не прочитана')} · similarity ${best.similarity||0}%</span>`:'<span>Автоматического совпадения нет. Это может быть кандидат под новый листинг.</span>'}</div><div class="price">${x.price?esc(x.price):'—'}</div><div class="actions"><button class="btn secondary" onclick="saveCandidate(${i})">В базу</button></div></div>`}).join('')}
function saveCandidate(i){const x=scanData[i],a=x.amazon||{},b=a.best||{};db.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),name:x.name||'Без названия',status:'research',supplierUrl:x.url||$('scanUrl').value,amazonUrl:b.url||a.searchUrl||'',asin:b.asin||'',marketplace:$('market').value,supplierPrice:parseFloat(x.price)||0,amazonPrice:parseFloat(String(b.price||'').replace(/[^0-9.,]/g,'').replace(',','.'))||0,moq:0,shipping:0,duty:0,prep:0,referral:15,fba:0,vat:20,ppc:0,storage:0,returns:0,notes:a.state==='not_found'?'Точного совпадения на Amazon не найдено. Проверить как потенциальный новый листинг.':'',updatedAt:Date.now()});persist();alert('Добавлено в базу')}
function saveAll(){scanData.forEach((_,i)=>saveCandidate(i))}
function renderDb(){let list=[...db],q=$('search')?.value?.toLowerCase()||'',st=$('statusFilter')?.value||'all';if(q)list=list.filter(x=>JSON.stringify(x).toLowerCase().includes(q));if(st!=='all')list=list.filter(x=>x.status===st);if($('sort')?.value==='roi')list.sort((a,b)=>calc(b).roi-calc(a).roi);else if($('sort')?.value==='profit')list.sort((a,b)=>calc(b).profit-calc(a).profit);else list.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));$('dbRows').innerHTML=list.map(x=>{const c=calc(x);return `<div class="row" onclick="editItem('${x.id}')"><div class="name">${esc(x.name)}</div><div>${money(x.amazonPrice)}</div><div>${money(c.landed)}</div><div class="${c.profit>=0?'green':'red'}">${money(c.profit)}</div><div>${c.margin.toFixed(1)}%</div><div>${c.roi.toFixed(1)}%</div><div>${esc(x.status||'research')}</div></div>`}).join('');$('dbEmpty').classList.toggle('hidden',!!list.length);$('dbTotal').textContent=db.length;$('dbShort').textContent=db.filter(x=>x.status==='shortlist').length;const cs=db.map(calc);$('dbRoi').textContent=(cs.length?cs.reduce((s,c)=>s+c.roi,0)/cs.length:0).toFixed(1)+'%';$('dbProfit').textContent=money(cs.length?cs.reduce((s,c)=>s+c.profit,0)/cs.length:0)}
function switchView(v){$('scannerView').classList.toggle('hidden',v!=='scanner');$('databaseView').classList.toggle('hidden',v!=='database');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='database')renderDb()}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>switchView(x.dataset.view));$('scanBtn').onclick=scan;$('saveAll').onclick=saveAll;['search','statusFilter','sort'].forEach(id=>$(id).addEventListener('input',renderDb));renderDb();