const MARKETPLACES={UK:'https://www.amazon.co.uk',US:'https://www.amazon.com',DE:'https://www.amazon.de'};
function clean(v=''){return String(v).replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim()}
function abs(base,href){try{return new URL(href,base).href}catch{return''}}
function safe(v){try{const u=new URL(v);if(!/^https?:$/.test(u.protocol))return null;const h=u.hostname.toLowerCase();if(h==='localhost'||h==='127.0.0.1'||h==='::1'||h.endsWith('.local')||/^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|169\.254\.)/.test(h))return null;return u}catch{return null}}
function send(res,status,body){res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(body))}
async function get(url,ms=5000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36','accept':'text/html,application/xhtml+xml,*/*;q=0.8','accept-language':'en-US,en;q=0.9'}});if(!r.ok)throw new Error('HTTP '+r.status);const type=r.headers.get('content-type')||'';if(!type.includes('text/html')&&!type.includes('application/xhtml+xml'))throw new Error('Unsupported content type');return await r.text()}finally{clearTimeout(t)}}
function meta(html,key){for(const p of [new RegExp(`<meta[^>]+(?:property|name)=["']${key}["'][^>]+content=["']([^"']+)["']`,'i'),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${key}["']`,'i')]){const m=html.match(p);if(m)return clean(m[1])}return''}
function titleOf(html){return clean(meta(html,'og:title')||meta(html,'twitter:title')||((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||''))}
function imageOf(html,base){const x=meta(html,'og:image')||meta(html,'twitter:image');return x?abs(base,x):''}
function priceOf(html){for(const v of [meta(html,'product:price:amount'),meta(html,'og:price:amount')])if(v)return v;const m=html.match(/(?:£|\$|€|US\$|USD|EUR|GBP)\s?([0-9]+(?:[.,][0-9]{1,2})?)/i);return m?m[1].replace(',','.') : ''}
function jsonLdProducts(html,base){const out=[];const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{const data=JSON.parse(m[1]);const q=Array.isArray(data)?[...data]:[data];while(q.length){const x=q.shift();if(!x||typeof x!=='object')continue;if(Array.isArray(x['@graph']))q.push(...x['@graph']);const typ=x['@type'];if(typ==='Product'||(Array.isArray(typ)&&typ.includes('Product'))){const offer=Array.isArray(x.offers)?x.offers[0]:x.offers||{};const img=Array.isArray(x.image)?x.image[0]:x.image||'';out.push({name:clean(x.name||''),url:abs(base,x.url||base),image:abs(base,img),price:String(offer.price||''),currency:String(offer.priceCurrency||'')})}}}catch{}}return out}
function productLinks(html,base,max){const host=new URL(base).host,out=[],seen=new Set();const re=/<a\b[^>]*href=["']([^"'#]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&out.length<max*5){const href=abs(base,m[1]);if(!href||seen.has(href))continue;let u;try{u=new URL(href)}catch{continue}if(u.host!==host)continue;const txt=clean(m[2]);if(txt.length<3||txt.length>220)continue;const p=u.pathname.toLowerCase();if(!(/product|item|goods|detail|offer|sku|shop|p\//.test(p)||/product|item|buy|shop/i.test(txt)))continue;seen.add(href);out.push({name:txt,url:href,image:'',price:'',currency:''})}return out.slice(0,max)}
function tokens(s){return new Set(clean(s).toLowerCase().replace(/[^a-z0-9а-яёіїєґ]+/gi,' ').split(/\s+/).filter(x=>x.length>2))}
function similarity(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(A.size,B.size)}
function parseAmazon(html,base){const out=[],seen=new Set();const re=/<div[^>]+data-asin=["']([A-Z0-9]{10})["'][\s\S]*?(?=<div[^>]+data-asin=|$)/gi;let m;while((m=re.exec(html))&&out.length<5){const block=m[0],asin=m[1];if(seen.has(asin))continue;seen.add(asin);const title=clean(((block.match(/<h2[^>]*>[\s\S]*?<span[^>]*>([\s\S]*?)<\/span>/i)||[])[1]||''));if(!title)continue;const price=clean(((block.match(/<span class=["'][^"']*a-offscreen[^"']*["'][^>]*>([^<]+)<\/span>/i)||[])[1]||''));out.push({asin,title,price,url:base+'/dp/'+asin})}return out}
async function amazonMatch(name,market){const base=MARKETPLACES[market]||MARKETPLACES.UK,searchUrl=base+'/s?k='+encodeURIComponent(name);try{const html=await get(searchUrl,4200);const items=parseAmazon(html,base).map(x=>({...x,similarity:Math.round(similarity(name,x.title)*100)})).sort((a,b)=>b.similarity-a.similarity);const best=items[0]||null;let state='not_found';if(best&&best.similarity>=55)state='found';else if(best&&best.similarity>=25)state='similar';return{state,searchUrl,best,items}}catch(e){return{state:'needs_review',searchUrl,best:null,items:[],note:'Amazon не дал автоматический ответ. Открой ручной поиск.'}}}
module.exports=async function handler(req,res){try{if(req.method!=='POST')return send(res,405,{error:'POST only'});let body=req.body||{};if(typeof body==='string'){try{body=JSON.parse(body)}catch{body={}}}const u=safe(body.url);if(!u)return send(res,400,{error:'Некорректный URL'});const market=body.marketplace||'UK';const max=Math.max(1,Math.min(Number(body.maxProducts)||8,12));let html;try{html=await get(u.href,6500)}catch(e){return send(res,200,{source:{url:u.href,host:u.host,title:''},marketplace:market,count:0,products:[],warning:'Сайт поставщика не дал автоматический доступ: '+e.message})}
let candidates=jsonLdProducts(html,u.href);if(!candidates.length){const pageTitle=titleOf(html);if(pageTitle)candidates.push({name:pageTitle,url:u.href,image:imageOf(html,u.href),price:priceOf(html),currency:''})}for(const x of productLinks(html,u.href,max))if(!candidates.some(c=>c.url===x.url))candidates.push(x);candidates=candidates.filter(x=>x.name).slice(0,max);const batches=[];for(let i=0;i<candidates.length;i+=4){const part=candidates.slice(i,i+4);const checked=await Promise.all(part.map(async c=>({...c,amazon:await amazonMatch(c.name,market)})));batches.push(...checked)}return send(res,200,{source:{url:u.href,host:u.host,title:titleOf(html)},marketplace:market,count:batches.length,products:batches,notes:['Быстрый режим: сканируем каталог без глубокого обхода каждой карточки.','Если Amazon блокирует автоматический запрос, сохраняем ссылку на ручной поиск.']})}catch(e){return send(res,200,{count:0,products:[],error:'Ошибка сканера',details:e&&e.message?e.message:String(e)})}}
