const MARKETPLACES={UK:'https://www.amazon.co.uk',US:'https://www.amazon.com',DE:'https://www.amazon.de'};

function clean(v=''){return String(v).replace(/<[^>]*>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim()}
function abs(base,href){try{return new URL(href,base).href}catch{return''}}
function safe(v){try{const u=new URL(v);if(!/^https?:$/.test(u.protocol))return null;const h=u.hostname.toLowerCase();if(h==='localhost'||h==='127.0.0.1'||h==='::1'||h.endsWith('.local')||/^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|169\.254\.)/.test(h))return null;return u}catch{return null}}
function send(res,status,body){res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(body))}
async function get(url,ms=5500){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal,redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36','accept':'text/html,application/xhtml+xml,*/*;q=0.8','accept-language':'en-US,en;q=0.9'}});if(!r.ok)throw new Error('HTTP '+r.status);const type=r.headers.get('content-type')||'';if(!type.includes('text/html')&&!type.includes('application/xhtml+xml'))throw new Error('Unsupported content type');return await r.text()}finally{clearTimeout(t)}}
function meta(html,key){for(const p of [new RegExp(`<meta[^>]+(?:property|name)=["']${key}["'][^>]+content=["']([^"']+)["']`,'i'),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${key}["']`,'i')]){const m=html.match(p);if(m)return clean(m[1])}return''}
function titleOf(html){return clean(meta(html,'og:title')||meta(html,'twitter:title')||((html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]||''))}
function imageOf(html,base){const x=meta(html,'og:image')||meta(html,'twitter:image');return x?abs(base,x):''}
function priceOf(html){for(const v of [meta(html,'product:price:amount'),meta(html,'og:price:amount')])if(v)return v;const m=html.match(/(?:£|\$|€|US\$|USD|EUR|GBP|CNY|RMB|¥)\s?([0-9]+(?:[.,][0-9]{1,2})?)/i);return m?m[1].replace(',','.') : ''}
function currencyOf(html){const c=meta(html,'product:price:currency')||meta(html,'og:price:currency');if(c)return c.toUpperCase();if(/(?:CNY|RMB|¥)/i.test(html))return'CNY';if(/(?:GBP|£)/i.test(html))return'GBP';if(/(?:EUR|€)/i.test(html))return'EUR';if(/(?:US\$|USD|\$)/i.test(html))return'USD';return''}
function jsonLdProducts(html,base){const out=[];const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{const data=JSON.parse(m[1]);const q=Array.isArray(data)?[...data]:[data];while(q.length){const x=q.shift();if(!x||typeof x!=='object')continue;if(Array.isArray(x['@graph']))q.push(...x['@graph']);if(Array.isArray(x.itemListElement))q.push(...x.itemListElement.map(y=>y.item||y));const typ=x['@type'];if(typ==='Product'||(Array.isArray(typ)&&typ.includes('Product'))){const offer=Array.isArray(x.offers)?x.offers[0]:x.offers||{};const img=Array.isArray(x.image)?x.image[0]:x.image||'';out.push({name:clean(x.name||''),url:abs(base,x.url||base),image:abs(base,img),price:String(offer.price||''),currency:String(offer.priceCurrency||'')})}}}catch{}}return out}
const GENERIC=/^(products?|shop|catalog|categories|home|about|contact|news|blog|read more|view more|learn more|details?|all products?)$/i;
function anchors(html,base){const out=[];const re=/<a\b[^>]*href=["']([^"'#]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const href=abs(base,m[1]);if(!href)continue;const txt=clean(m[2]);out.push({href,txt})}return out}
function productLinks(html,base,max){const host=new URL(base).host,out=[],seen=new Set();for(const a of anchors(html,base)){if(out.length>=max*8)break;let u;try{u=new URL(a.href)}catch{continue}if(u.host!==host||seen.has(a.href))continue;const txt=a.txt;if(txt.length<5||txt.length>180||GENERIC.test(txt))continue;const p=u.pathname.toLowerCase();if(!(/\/products?\/|\/product-|\/item\/|\/goods\/|\/detail\/|\/sku\/|\/p\//.test(p)))continue;seen.add(a.href);out.push({name:txt,url:a.href,image:'',price:'',currency:''})}return out.slice(0,max)}
function categoryLinks(html,base,max=5){const host=new URL(base).host,out=[],seen=new Set();for(const a of anchors(html,base)){if(out.length>=max)break;let u;try{u=new URL(a.href)}catch{continue}if(u.host!==host||seen.has(a.href))continue;const p=u.pathname.toLowerCase();if(!(/collection|category|catalog|shop|products/.test(p)))continue;if(/\/products?\/[^/]+/.test(p))continue;seen.add(a.href);out.push(a.href)}return out}
function detailFallback(html,url){const name=titleOf(html),image=imageOf(html,url),price=priceOf(html),currency=currencyOf(html);if(!name)return null;return{name,url,image,price,currency}}
const STOP=new Set(['with','for','the','and','from','this','that','new','pack','set','usb','type','port','ports','charger','charging','adapter','wall','plug']);
function tokens(s){return new Set(clean(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x.length>1&&!STOP.has(x)))}
function similarity(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;const sourceCoverage=hit/A.size,targetCoverage=hit/B.size;return .75*sourceCoverage+.25*targetCoverage}
function parseAmazon(html,base){const out=[],seen=new Set();const blocks=html.split(/(?=<div[^>]+data-component-type=["']s-search-result["'])/i);for(const block of blocks){const asin=((block.match(/data-asin=["']([A-Z0-9]{10})["']/i)||[])[1]||'');if(!asin||seen.has(asin))continue;const title=clean(((block.match(/<h2[^>]*>[\s\S]*?<span[^>]*>([\s\S]*?)<\/span>/i)||[])[1]||((block.match(/aria-label=["']([^"']{10,220})["']/i)||[])[1]||''));if(!title)continue;const price=clean(((block.match(/<span class=["'][^"']*a-offscreen[^"']*["'][^>]*>([^<]+)<\/span>/i)||[])[1]||''));seen.add(asin);out.push({asin,title,price,url:base+'/dp/'+asin});if(out.length>=10)break}return out}
function explicitNoResults(html){return /no results for|did not match any products|keine ergebnisse|keine treffer/i.test(clean(html.slice(0,120000)))}
function compactQuery(name){const parts=clean(name).replace(/[|®™]/g,' ').split(/\s+/).filter(Boolean);return parts.slice(0,9).join(' ')}
async function amazonSearch(query,base){const searchUrl=base+'/s?k='+encodeURIComponent(query);const html=await get(searchUrl,4800);return{searchUrl,html,items:parseAmazon(html,base)}}
async function amazonMatch(name,market){const base=MARKETPLACES[market]||MARKETPLACES.US;const queries=[name,compactQuery(name)].filter((q,i,a)=>q&&a.indexOf(q)===i);let all=[],searchUrl=base+'/s?k='+encodeURIComponent(name),sawNoResults=false;try{for(const q of queries){const r=await amazonSearch(q,base);searchUrl=r.searchUrl;sawNoResults=sawNoResults||explicitNoResults(r.html);all.push(...r.items);if(r.items.length)break}const byAsin=new Map();for(const x of all)if(!byAsin.has(x.asin))byAsin.set(x.asin,x);const items=[...byAsin.values()].map(x=>({...x,similarity:Math.round(similarity(name,x.title)*100)})).sort((a,b)=>b.similarity-a.similarity).slice(0,6);const best=items[0]||null;if(best&&best.similarity>=52)return{state:'found',searchUrl,best,items,verified:true};if(items.length||sawNoResults)return{state:'not_found',searchUrl,best:null,items,verified:true};return{state:'unverified',searchUrl,best:null,items:[],verified:false,note:'Amazon page could not be parsed reliably.'}}catch(e){return{state:'unverified',searchUrl,best:null,items:[],verified:false,note:'Amazon blocked or timed out.'}}}
function dedupe(items){const seen=new Set(),out=[];for(const x of items){const key=(x.url||'')+'|'+(x.name||'').toLowerCase();if(!x.name||GENERIC.test(x.name)||seen.has(key))continue;seen.add(key);out.push(x)}return out}

module.exports=async function handler(req,res){try{
  if(req.method!=='POST')return send(res,405,{error:'POST only'});
  let body=req.body||{};if(typeof body==='string'){try{body=JSON.parse(body)}catch{body={}}}
  const u=safe(body.url);if(!u)return send(res,400,{error:'Некорректный URL'});
  const market=body.marketplace||'US';const max=Math.max(1,Math.min(Number(body.maxProducts)||16,20));
  let html;try{html=await get(u.href,7500)}catch(e){return send(res,200,{source:{url:u.href,host:u.host,title:''},marketplace:market,count:0,products:[],warning:'Сайт поставщика не дал автоматический доступ: '+e.message})}
  let candidates=[...jsonLdProducts(html,u.href),...productLinks(html,u.href,max)];
  if(candidates.length<Math.min(6,max)){
    const cats=categoryLinks(html,u.href,4);
    const pages=await Promise.all(cats.map(async url=>{try{return{url,html:await get(url,3800)}}catch{return null}}));
    for(const p of pages.filter(Boolean))candidates.push(...jsonLdProducts(p.html,p.url),...productLinks(p.html,p.url,max));
  }
  if(!candidates.length){const single=detailFallback(html,u.href);if(single)candidates.push(single)}
  candidates=dedupe(candidates).slice(0,max);
  const detailed=[];
  for(let i=0;i<candidates.length;i+=6){const batch=candidates.slice(i,i+6);const part=await Promise.all(batch.map(async c=>{if(!c.url||c.url===u.href)return c;try{const h=await get(c.url,3600);return{...c,name:titleOf(h)||c.name,image:imageOf(h,c.url)||c.image,price:priceOf(h)||c.price,currency:currencyOf(h)||c.currency}}catch{return c}}));detailed.push(...part)}
  const checked=[];
  for(let i=0;i<detailed.length;i+=4){const batch=detailed.slice(i,i+4);const part=await Promise.all(batch.map(async c=>({...c,amazon:await amazonMatch(c.name,market)})));checked.push(...part)}
  return send(res,200,{source:{url:u.href,host:u.host,title:titleOf(html)},marketplace:market,count:checked.length,products:checked,mode:'compact_fba_scan'});
}catch(e){return send(res,200,{count:0,products:[],error:'Ошибка сканера',details:e&&e.message?e.message:String(e)})}}
